FROM node:lts AS builder

WORKDIR /app
COPY ./front/package.json ./front/package-lock.json ./
RUN npm install
COPY ./front .
RUN npm run build
FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
